services:
  db:
    image: postgres:17.6
    container_name: delivery_db
    environment:
      POSTGRES_PASSWORD: 1998
      POSTGRES_DB: delivery_db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d delivery_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:8.2.1
    container_name: delivery_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: delivery_worker
    command: celery -A delivery.background_task.celery.celery worker -P solo
    volumes:
      - .:/app
    depends_on:
      - app

  celery_beat:
    build: .
    container_name: delivery_beat
    command: celery -A delivery.background_task.celery.celery beat
    volumes:
      - .:/app
    depends_on:
      - app

  app:
    build: .
    container_name: delivery_app
    command: sh -c "alembic upgrade head && uvicorn src.delivery.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  pgdata:
